webapp/urls.py
from django.urls import path

from webapp.views.products import IndexView, CreateProductView, UpdateProductView, DeleteProduct, DetailProductView
from webapp.views.reviews import CreateReviewView, UpdateReviewView, DeleteReviewView, ListNotModeratedReviewView

app_name = "webapp"

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('products/add/', CreateProductView.as_view(), name="create_product"),
    path('products/<int:pk>/', DetailProductView.as_view(), name="product_view"),
    path('products/<int:pk>/update/', UpdateProductView.as_view(), name="update_product"),
    path('products/<int:pk>/delete/', DeleteProduct.as_view(), name="delete_product"),
    path('products/<int:pk>/review/add/', CreateReviewView.as_view(), name="review_create"),
    path('reviews/<int:pk>/update/', UpdateReviewView.as_view(), name="update_review"),
    path('reviews/<int:pk>/delete/', DeleteReviewView.as_view(), name="delete_review"),
    path('reviews/not-moderated/', ListNotModeratedReviewView.as_view(), name="not_moderated_reviews"),
]

webinar23/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
    path('accounts/', include("accounts.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import Avg

CHOISES = [('other', 'Разное'), ('phones', 'Телефоны'), ('headphones', 'Наушники'), ('cases', 'Чехол')]


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    category = models.CharField(max_length=20, default='other', choices=CHOISES, verbose_name='Категории')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание')
    picture = models.ImageField(verbose_name='Картинка', upload_to='pictures', null=True, blank=True)

    class Meta:
        db_table = "products"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self):
        return f"{self.name} - {self.category}"

    def get_avg(self):
        result = self.reviews.filter(is_moderated=True).aggregate(avg=Avg("mark"))
        return result["avg"]


class Review(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='reviews', verbose_name='Автор')
    product = models.ForeignKey('webapp.Product', on_delete=models.CASCADE, related_name='reviews',
                                verbose_name='Товар')
    text = models.TextField(max_length=2000, verbose_name='Текст отзыва')
    mark = models.IntegerField(verbose_name='Оценка', validators=[MaxValueValidator(5), MinValueValidator(1)])
    is_moderated = models.BooleanField(verbose_name='Подтвержден', default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    edited_at = models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')

    class Meta:
        db_table = "reviews"
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        permissions = [("view_not_moderated_review", "Видеть немодерированные отзывы")]

    def __str__(self):
        return f"{self.author.username} - {self.product.name}"

webapp/forms.py
from django import forms

from webapp.models import Product, Review
from django.forms import widgets


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "description", "category", "picture"]
        widgets = {"description": widgets.Textarea}


class UserReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["text", "mark"]
        widgets = {"text": widgets.Textarea}


class ModeratorReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["text", "mark", "is_moderated"]
        widgets = {"text": widgets.Textarea}

webapp/views.py
from django.shortcuts import render

# Create your views here.

webapp/views/products.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProductForm
from webapp.models import Product


class IndexView(ListView):
    model = Product
    template_name = "products/index.html"
    context_object_name = "products"
    paginate_by = 6


class DetailProductView(DetailView):
    template_name = "products/detail.html"
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = self.object.reviews.all()
        if not self.request.user.has_perm("webapp.view_not_moderated_review"):
            reviews = reviews.filter(is_moderated=True)
        context['reviews'] = reviews.order_by("-edited_at")
        return context


class CreateProductView(CreateView):
    form_class = ProductForm
    template_name = "products/create.html"

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.pk})


class UpdateProductView(PermissionRequiredMixin, UpdateView):
    form_class = ProductForm
    template_name = "products/update.html"
    model = Product
    permission_required = "webapp.change_product"

    # def has_permission(self):
    #     return self.request.user.has_perm("webapp.change_product")
    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.pk})


class DeleteProduct(PermissionRequiredMixin, DeleteView):
    model = Product
    template_name = "products/delete.html"
    success_url = reverse_lazy('webapp:index')
    permission_required = "webapp.delete_product"

webapp/views/reviews.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView
from django.shortcuts import get_object_or_404

from webapp.forms import UserReviewForm, ModeratorReviewForm
from webapp.models import Product, Review


class CreateReviewView(LoginRequiredMixin, CreateView):
    form_class = UserReviewForm
    template_name = "reviews/create.html"

    def form_valid(self, form):
        product = get_object_or_404(Product, pk=self.kwargs.get("pk"))
        author = self.request.user
        form.instance.author = author
        form.instance.product = product
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class UpdateReviewView(PermissionRequiredMixin, UpdateView):
    form_class = UserReviewForm
    template_name = "reviews/update.html"
    permission_required = "webapp.change_review"
    model = Review

    def get_form_class(self):
        if self.request.user.has_perm("webapp.change_review"):
            return ModeratorReviewForm
        return UserReviewForm

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class DeleteReviewView(PermissionRequiredMixin, DeleteView):
    permission_required = "webapp.change_review"
    model = Review

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

    def has_permission(self):
        return super().has_permission() or self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse("webapp:product_view", kwargs={"pk": self.object.product.pk})


class ListNotModeratedReviewView(PermissionRequiredMixin, ListView):
    queryset = Review.objects.filter(is_moderated=False)
    context_object_name = "reviews"
    template_name = "reviews/not_moderated.html"
    permission_required = "webapp.view_not_moderated_review"

webapp/templates/products/create.html
{% extends "base.html" %}
{% block title %}Создание продукта{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Создание продукта</h1>
        <form action="" method="post" enctype="multipart/form-data">
            {% include "partial/form.html" with button_text="Создать" %}
        </form>
        <a href="{% url "webapp:index" %}">На главную</a>
    </div>
{% endblock %}

webapp/templates/products/delete.html
{% extends "base.html" %}
{% block title %}Удаление продукта{% endblock %}

{% block content %}
    <h2>вы действительно хотите удалить продукт {{ product.name }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        <button class="btn" type="submit">Да</button>
    </form>
    <a class="btn" href="{% url "webapp:product_view" product.pk %}">Нет</a>
{% endblock %}

webapp/templates/products/detail.html
{% extends "base.html" %}
{% load static %}
{% block nav %}

    {% if perms.webapp.change_product %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:update_product" product.pk %}">Редактировать</a>
        </li>
    {% endif %}

    {% if perms.webapp.delete_product %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:delete_product" product.pk %}">Удалить</a>
        </li>
    {% endif %}
        {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:review_create" product.pk %}">Добавить отзыв</a>
        </li>
        {% endif %}
{% endblock %}

{% block content %}
    <div class="card mt-3">
        <div class="card-body text-center">
            <h5 class="card-title">{{ product.name }} | {{ product.get_avg }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">Автор: {{ product.category }}</h6>
            <p class="card-text">{{ article.description }}</p>
            {% if product.picture %}
                <img src="{{ product.picture.url }}" alt="#">
            {% else %}
                <img src="{% static "images/image.jpg" %}" alt="">
            {% endif %}

        </div>
    </div>
    {% include "partial/reviews_list_partial.html" %}
{% endblock %}

webapp/templates/products/index.html
{% extends "base.html" %}
{% load static %}
{% block nav %}
    {% if perms.webapp.add_product %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:create_product" %}">Создание продукта</a>
        </li>
    {% endif %}
    {% if perms.webapp.view_not_moderated_review %}
        <li class="nav-item">
            <a class="nav-link" href="{% url "webapp:not_moderated_reviews" %}">Непромодерированные отзывы</a>
        </li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1 class="text-center">Продукты</h1>
    <div class="row">
        {% for product in products %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.name }} | {{ product.get_avg }}</h5>
                        <p>{{ product.category }}</p>
                    </div>
                    <a href="{% url "webapp:product_view" product.pk %}" class="card-link btn btn-primary">Подробнее</a>
                </div>
            </div>
        {% empty %}
        {% endfor %}
        {% if is_paginated %}
            <div class="text-center">{% include "partial/pagination.html" %}</div>
        {% endif %}
    </div>
{% endblock %}

webapp/templates/products/update.html
{% extends "base.html" %}
{% block title %}Изменение продукта{% endblock %}

{% block content %}
    <div class="text-center">
        <h1>Изменение продукта</h1>
        <form action="" method="post">
            {% include "partial/form.html" with button_text="Изменить" %}
        </form>
        <a href="{% url "webapp:index" %}">На главную</a>
    </div>
{% endblock %}